[package]
name = "byte-calculator"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "2.2.0"

[dev-dependencies]
solana-client = "2.2.0"
solana-sdk = "2.2.0"

[[example]]
name = "client"
path = "examples/client.rs"